# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # メインブランチにプッシュされたとき実行
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 手動でも実行
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: echo "$SSH_PRIVATE_KEY" > .ssh/key && chmod 600 .ssh/key

      - name: Deploy to VPS
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: rsync -ahvn --checksum --delete 
            -e "ssh -i .ssh/key -p ${DEPLOY_PORT} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" 
            ./src/* ${DEPLOY_USER}@${DEPLOY_HOST}:~/reverse_proxy/
